In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
from Univariate import univariate
un = univariate

In [5]:
un.QuanQual(dataset)

(['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'],
 ['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'])

In [6]:
qual,quan = un.QuanQual(dataset)

In [7]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [8]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [9]:
table = un.Descriptive_Table(dataset,quan)

In [10]:
un.Frequency("ssc_p",dataset)

     Unique Values  Frequency  Relative Frequency     Cusum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [11]:
un.Frequency("hsc_p",dataset)

    Unique Values  Frequency  Relative Frequency     Cusum
0           63.00         14            0.144330  0.144330
1           62.00         12            0.123711  0.268041
2           60.00          9            0.092784  0.360825
3           67.00          9            0.092784  0.453608
4           64.00          8            0.082474  0.536082
..            ...        ...                 ...       ...
92          77.60          1            0.010309  2.175258
93          70.20          1            0.010309  2.185567
94          61.40          1            0.010309  2.195876
95          61.33          1            0.010309  2.206186
96          42.00          1            0.010309  2.216495

[97 rows x 4 columns]

In [12]:
un.Frequency("degree_p",dataset)

    Unique Values  Frequency  Relative Frequency     Cusum
0           65.00         20            0.224719  0.224719
1           66.00         13            0.146067  0.370787
2           72.00         12            0.134831  0.505618
3           64.00         11            0.123596  0.629213
4           58.00          9            0.101124  0.730337
..            ...        ...                 ...       ...
84          64.80          1            0.011236  2.370787
85          56.30          1            0.011236  2.382022
86          91.00          1            0.011236  2.393258
87          56.87          1            0.011236  2.404494
88          77.60          1            0.011236  2.415730

[89 rows x 4 columns]

In [13]:
un.Outlier_Columns(table,quan)

(['hsc_p'], ['hsc_p', 'degree_p', 'salary'])

In [14]:
Lesser_outlier,Greater_outlier = un.Outlier_Columns(table,quan)

In [15]:
Lesser_outlier

['hsc_p']

In [16]:
Greater_outlier

['hsc_p', 'degree_p', 'salary']

In [17]:
un.Replace_Outliers(Lesser_outlier,Greater_outlier,table,dataset)

In [18]:
table = un.Descriptive_Table(dataset,quan)

In [19]:
Lesser_outlier,Greater_outlier = un.Outlier_Columns(table,quan)

In [20]:
Lesser_outlier

[]

In [21]:
Greater_outlier

[]

In [22]:
table

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5_Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0